# Generated by Django 5.2.10 on 2026-01-11 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, help_text='Sales order code', max_length=30)),
                ('total_quantity', models.PositiveIntegerField()),
                ('batch_size', models.PositiveIntegerField()),
                ('number_of_batches', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'production_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.productionorder')),
            ],
            options={
                'db_table': 'production_batch',
                'ordering': ['created_at'],
            },
        ),
    ]
