# Generated by Django 5.2.10 on 2026-01-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='planning_decided_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when Planning approved/rejected the order', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='planning_decision_reason',
            field=models.TextField(blank=True, help_text='Reason provided by Planning if order is rejected', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='planning_status',
            field=models.CharField(blank=True, help_text='Mirror of PlanningRequest.status', max_length=20, null=True),
        ),
    ]
