# Generated by Django 5.2.10 on 2026-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder_planning_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='product_title',
            field=models.CharField(blank=True, help_text='Short business-friendly product name', max_length=255, null=True),
        ),
    ]
