# Generated by Django 5.2.10 on 2026-01-11 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated')], default='DRAFT', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_recipe', to='production.productionbatch')),
            ],
            options={
                'db_table': 'qc_recipe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCRecipeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='Quantity required per batch', max_digits=12)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qc.qcrecipe')),
            ],
            options={
                'db_table': 'qc_recipe_item',
            },
        ),
    ]
