# Generated by Django 5.2.10 on 2026-01-11 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_journalline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Event type (BATCH_CONSUMPTION, GRN_RECEIPT, etc.)', max_length=50)),
                ('source_type', models.CharField(help_text='Source module (PRODUCTION, INVENTORY, PROCUREMENT)', max_length=50)),
                ('source_reference', models.CharField(help_text='Source identifier (batch_id, grn_no, etc.)', max_length=100)),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_event', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'accounting_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
