# Generated by Django 5.2.9 on 2026-01-08 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed (CREATE_USER, UPDATE_ROLE, LOGIN, etc.)', max_length=100)),
                ('module', models.CharField(help_text='System module (USERS, INVENTORY, SECURITY, SYSTEM)', max_length=50)),
                ('object_id', models.CharField(blank=True, help_text='Affected object identifier (if any)', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional contextual data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='admin_activ_action_b4cf28_idx'), models.Index(fields=['module'], name='admin_activ_module_819228_idx'), models.Index(fields=['created_at'], name='admin_activ_created_7b489d_idx')],
            },
        ),
    ]
