# Generated by Django 5.2.10 on 2026-01-11 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, max_length=30)),
                ('customer_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_description', models.TextField()),
                ('is_new_product', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('requested_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'planning_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
