# Generated by Django 5.2.10 on 2026-01-11 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_planningrequest_decided_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, help_text='Sales order code', max_length=30)),
                ('production_order_id', models.UUIDField(help_text='Linked ProductionOrder ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RELEASED', 'Released'), ('CLOSED', 'Closed')], default='CREATED', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchase_requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='Quantity to procure', max_digits=12)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.purchaserequisition')),
            ],
            options={
                'db_table': 'purchase_requisition_item',
            },
        ),
    ]
