# Generated by Django 5.2.10 on 2026-01-11 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, max_length=30)),
                ('product_description', models.TextField()),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rd_new_product_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
