# Generated by Django 5.2.9 on 2026-01-07 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='Unique inventory item code', max_length=100, unique=True)),
                ('item_name', models.CharField(help_text='Human readable item name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('inventory_nature', models.CharField(choices=[('RAW', 'Raw Material'), ('PACK', 'Packaging'), ('FG', 'Finished Goods')], max_length=50)),
                ('inventory_usage', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('TECHNICAL', 'Technical'), ('SALE', 'For Sale')], max_length=50)),
                ('procurement_type', models.CharField(choices=[('PURCHASED', 'Purchased'), ('MANUFACTURED', 'Manufactured')], max_length=50)),
                ('hazard_class', models.CharField(blank=True, choices=[('NONE', 'Non Hazardous'), ('FLAMMABLE', 'Flammable'), ('TOXIC', 'Toxic'), ('CORROSIVE', 'Corrosive')], max_length=50)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, help_text='Shelf life in days', null=True)),
                ('expiry_tracking_required', models.BooleanField(default=False)),
                ('item_status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Deprecated', 'Deprecated')], default='Draft', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='System derived. Do not edit manually.')),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('receiving_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_available', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qc_status', models.CharField(choices=[('QC_PENDING', 'QC Pending'), ('QC_APPROVED', 'QC Approved'), ('QC_BLOCKED', 'QC Blocked'), ('EXPIRED', 'Expired')], default='QC_PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RESERVE', 'Reserve Stock'), ('RELEASE', 'Release Reserved Stock')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
