# Generated by Django 5.2.9 on 2026-01-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybatch',
            options={'ordering': ['-receiving_date']},
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='quantity_available',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybatch',
            unique_together={('inventory_item', 'batch_number')},
        ),
    ]
